version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ~/.mysql:/var/lib/mysql
    ports:
      - 3306:3306