version: "3.7"
services:
  redis-master:
    image: redis:5-alpine
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ~/.redis/master:/data

  redis-slave-1:
    image: redis:5-alpine
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6380 --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ~/.redis/slave1:/data

  redis-slave-2:
    image: redis:5-alpine
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6381 --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ~/.redis/slave2:/data

  sentinel1:
    image: redis:5-alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    ports:
      - 26379:26379
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis:5-alpine
    container_name: redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    ports:
      - 26380:26379
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis:5-alpine
    container_name: redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    ports:
      - 26381:26379
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
